// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlFUcXgBa8V1-wMvaXzQQgaHQcYWsw7AA',
    appId: '1:397750544437:web:617dbdd07cff45d6f8a97c',
    messagingSenderId: '397750544437',
    projectId: 'sign-in-8b325',
    authDomain: 'sign-in-8b325.firebaseapp.com',
    storageBucket: 'sign-in-8b325.appspot.com',
    measurementId: 'G-GHYE2ZB06C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvi0EiKo3ZfTg99YZRlyB8K8Vsr7M1_L0',
    appId: '1:397750544437:android:4bf3dd070cb5ba75f8a97c',
    messagingSenderId: '397750544437',
    projectId: 'sign-in-8b325',
    storageBucket: 'sign-in-8b325.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOX1TluaLgfRmXqDCMLLdFMTa6MmKvsvI',
    appId: '1:397750544437:ios:99c793d1e77c02e1f8a97c',
    messagingSenderId: '397750544437',
    projectId: 'sign-in-8b325',
    storageBucket: 'sign-in-8b325.appspot.com',
    androidClientId:
        '397750544437-jp1p4sejv935m7oqro5bnc2p1edu1liv.apps.googleusercontent.com',
    iosClientId:
        '397750544437-lgqt45f2saaksqh55k8e7l2gkek1np9d.apps.googleusercontent.com',
    iosBundleId: 'com.utadeo.coolstuffmarket.coolstuffMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOX1TluaLgfRmXqDCMLLdFMTa6MmKvsvI',
    appId: '1:397750544437:ios:99c793d1e77c02e1f8a97c',
    messagingSenderId: '397750544437',
    projectId: 'sign-in-8b325',
    storageBucket: 'sign-in-8b325.appspot.com',
    androidClientId:
        '397750544437-jp1p4sejv935m7oqro5bnc2p1edu1liv.apps.googleusercontent.com',
    iosClientId:
        '397750544437-lgqt45f2saaksqh55k8e7l2gkek1np9d.apps.googleusercontent.com',
    iosBundleId: 'com.utadeo.coolstuffmarket.coolstuffMarket',
  );
}
